### ISSUE TITLE
没有发送消息的能力吗？

### ISSUE THREAD

**Issue by jjeejj** [aliforever/go-tdlib#1]

**Comment by aliforever** [comment]
Hi.

I added [SendMessage](https://github.com/aliforever/go-tdlib/commit/b8b62a9872d70a45cf1a0dd8d448977229e0052e#diff-1b80e660fccb740c483bb23c07833bc1ef560c7cec2cdb6737a81bab03e3591d) 

The package doesn't contain all the methods, you can either fork a version for yourself or use following [method](https://github.com/aliforever/go-tdlib/blob/b8b62a9872d70a45cf1a0dd8d448977229e0052e/methods.go#L10) to fire other requests:

```go
result, err := client.CustomRequest("sendMessage",  map[string]interface{}{
		"@type": "sendMessage",
		"chat_id": 123456789,
		"input_message_content": map[string]interface{}{
			"@type": "inputMessageText",
			"text": map[string]interface{}{
				"@type": "formattedText",
				"text": "Hello World",
			},
		},
	}
)
if err != nil {
    panic(err)
}

fmt.Println(*result)
```

You can learn about available methods on tdlib documentation [website (sendMessage)](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1send_message.html)
