### ISSUE TITLE
Add Search Public Chat

### ISSUE THREAD

**Issue by WCY-dt** [aliforever/go-tdlib#5]
Is there a function that can receive a string input and then find the corresponding chat id number?
Example: [Arman92/go-tdlib - func (client *Client) SearchPublicChat(username string) (*Chat, error)](https://github.com/Arman92/go-tdlib/blob/f37751283a069bb8b812771d49ba9f2dcc28ca31/methods.go#L1112)

**Comment by aliforever** [comment]
Added in v0.2.16:
https://github.com/aliforever/go-tdlib/commit/d159dc69308ee66f19a8b0883d5d0f78f9a9dc52#diff-1b80e660fccb740c483bb23c07833bc1ef560c7cec2cdb6737a81bab03e3591dR313
